OtherExamples/GeneralExamples/Models/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GeneralExamples.Models
{
    public class Ogrenci
    {
        [Required]
        public string AdSoyad { get; set; }
        [Range(1,4)]
        public int Sinif { get; set; }
        [Range(0, 4.0)]
        public double Ortalama { get; set; }
    }
}

OtherExamples/GeneralExamples/Models/Siparis.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GeneralExamples.Models
{
    public class Siparis
    {
        public List<Urun> Urunler { get; set; }
    }
}

OtherExamples/GeneralExamples/Models/Urun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GeneralExamples.Models
{
    public class Urun
    {
        public string UrunAd { get; set; }
        public decimal Fiyat { get; set; }
        public int Adet { get; set; }
    }
}

OtherExamples/GeneralExamples/Controllers/ComplexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeneralExamples.Controllers
{
    public class Class1
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
    public class Class2
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
    public class ComplexViewModel
    {
        public List<Class1> Class1List { get; set; }
        public List<Class2> Class2List { get; set; }

        public ComplexViewModel()
        {
            Class1List = new List<Class1>();
            Class2List = new List<Class2>();
        }
    }
    public class ComplexController : Controller
    {
        // GET: Complex
        public ActionResult Index()
        {
            ComplexViewModel vm = new ComplexViewModel();
            for(int i = 0; i < 10; ++i)
            {
                vm.Class1List.Add(new Class1() { Id = i + 1, Value = "C1Val " + i + 1 });
                vm.Class2List.Add(new Class2() { Id = i + 1, Value = "C2Val " + i + 1 });
            }
            return View(model:vm);
        }
    }
}

OtherExamples/GeneralExamples/Controllers/OgrenciController.cs
using GeneralExamples.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeneralExamples.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ogrenci obj)
        {
            if (ModelState.IsValid)
            {
                return Content("Kayıt eklendi");
            }
            
            return RedirectToAction("Index");
        }
    }
}

OtherExamples/GeneralExamples/Controllers/SiparisController.cs
using GeneralExamples.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeneralExamples.Controllers
{
    public class SiparisController : Controller
    {
        // GET: Siparis
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Siparis sip)
        {
            return new EmptyResult();
        }
    }
}

OtherExamples/GeneralExamples/Controllers/YemekSepetiController.cs
using GeneralExamples.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeneralExamples.Controllers
{
    public class YemekSepetiController : Controller
    {
        private IEnumerable<Urun> DummyUrunOlustur()
        {
            var r = new Random();
            for (int i = 0; i < 10; i++)
                yield return new Urun()
                {
                    Adet = r.Next(1, 100),
                    Fiyat = (decimal)r.NextDouble() * 50,
                    UrunAd = "Yemek " + r.Next(4, 44) + i
                };
        }
        // GET: YemekSepeti
        public ActionResult Index()
        {
            return View(model:DummyUrunOlustur());
        }
    }
}

OtherExamples/GeneralExamples/Views/Complex/Index.cshtml
@using GeneralExamples.Controllers;
@model ComplexViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<ul>
    @foreach(var c1 in Model.Class1List)
    {
        <li>@c1.Value</li>
    }
</ul>
<ul>
    @foreach (var c2 in Model.Class2List)
    {
        <li>@c2.Value</li>
    }
</ul>

OtherExamples/GeneralExamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Siparis", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

OtherExamples/GeneralExamples/Views/Siparis/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Siparis Ekleme</h2>
<div class="row">
    <div class="col-md-2">
        <select id="lstUrunler" size="10" style="width:50%"></select>
    </div>
    <div class="col-md-4">
        <form id="frmEkle">
            <fieldset>
                <legend>
                    Siparişe ürün ekle
                </legend>
                <div class="form-group">
                    <label for="txtUrunAd">Ürün Ad :</label>
                    <input type="text" id="txtUrunAd" required class="form-control" />
                </div>
                <div class="form-group">
                    <label for="txtFiyat">Fiyat :</label>
                    <input type="text" id="txtFiyat" pattern="[0-9]+,[0-9]{2}" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="txtAdet">Adet :</label>
                    <input type="number" id="txtAdet" class="form-control" />
                </div>
                <div>
                    <button type="submit" id="btnEkle" class="btn btn-info">Ürün Ekle</button>
                </div>
            </fieldset>
           
        </form>
        <button class="btn btn-danger" id="btnSendServer">DBye Kaydet</button>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        var sepet = { Urunler: [] };
        var editingIndex = -1;
        $("#frmEkle").submit(function (e) {
            e.preventDefault();
            var urunData;
            if (editingIndex == -1)
                urunData = {};
            else
                urunData = sepet.Urunler[editingIndex];

            urunData.UrunAd = $(this).find("#txtUrunAd").val();
            urunData.Fiyat = $(this).find("#txtFiyat").val();
            urunData.Adet = $(this).find("#txtAdet").val();

            sepet.Urunler.push(urunData);

            if (editingIndex == -1)
                $("#lstUrunler").append($("<option>").text(urunData.UrunAd));
            //else
              //  $("#lstUrunler:nth-child("+(editingIndex+1)+")").text(urunData.UrunAd);
            this.reset();

            editingIndex = -1;
        });
        $("#lstUrunler").change(function () {
            console.log(this.selectedIndex);
            var obj = sepet.Urunler[this.selectedIndex];
            $("#txtUrunAd").val(obj.UrunAd);
            $("#txtFiyat").val(obj.Fiyat);
            $("#txtAdet").val(obj.Adet);

            editingIndex = this.selectedIndex;


        });

        $("#btnSendServer").click(function () {
            var options = {
                url: "/Siparis/Save",
                type: "POST",
                contentType: "application/json",
                data:JSON.stringify(sepet)
            };

            $.ajax(options).success(function () {
                alert("Başarılı bir şekilde kaydedildi!");
                sepet = { Urunler: [] };
                $("#lstUrunler").empty();
            }).error(function (xhr,status,error) {
                alert("Kaydetme başarısız oldu! " + error);
            });

        });
    </script>
}

OtherExamples/GeneralExamples/Views/YemekSepeti/Index.cshtml
@using GeneralExamples.Models;
@model IEnumerable<Urun>
@{
    ViewBag.Title = "Index";
}
<style>
    .urun{
        border:1px dashed red;
        padding:10px;
    }
    .urun button{
        display:inline;
    }
    #sepet {
        border:1px solid black;
        padding:10px;
    }
</style>
<h2>YS</h2>

<div class="row">
    <div class="col-md-3">
        <h3>Sepet</h3>
        <div id="sepet"></div>
    </div>
    <div class="col-md-9">
        @foreach(var urun in Model)
        {
            <div class="row urun" >
                <h3>@urun.UrunAd</h3>
                <h4 data-deger="@urun.Fiyat">@urun.Fiyat.ToString("c")</h4>
                <button class="btn btn-default" >Sepete Ekle</button>
            </div>
        }
    </div>
</div>
@section scripts{
    <script>
        var stored = JSON.parse(localStorage.getItem("sepet"));
        var sepet =  stored == null?{ Urunler: [], Toplam: 0 }:stored;
        PopulateSepet(sepet);
        function PopulateSepet(sepet) {
            if (sepet == undefined)
                return;
            $("#sepet").empty();
            sepet.Urunler.forEach(function (e) {
                var div = $("<div>")
               .append($("<h3>").text(e.YemekAd))
               .append($("<h4>").text(e.YemekFiyat))
               .append($("<button>").text("Kaldır"));

                $("#sepet").append(div);
            });
            
        }
        
        $(".urun button").click(function () {
            var fiyat = parseFloat($(this).prev().data("deger")),
                urunAd = $(this).prev().prev().text();
            var yemek = {
                YemekFiyat: fiyat,
                YemekAd : urunAd
            }
            sepet.Urunler.push(yemek);
            localStorage.setItem("sepet", JSON.stringify(sepet));
            UpdateToplam();
            PopulateSepet(sepet);
        });
        function UpdateToplam() {
            var toplamYemek = sepet.Urunler.reduce(function (prev,current) {
                return { YemekFiyat: prev.YemekFiyat + current.YemekFiyat };
            })
            sepet.Toplam = toplamYemek.YemekFiyat;
            /*
            var toplam = 0;
            for (var i = 0; i < sepet.Urunler.length; ++i) {
                toplam += sepet.Urunler[i].YemekFiyat;

            }
            sepet.Toplam = toplam;
            */
           
        }
    </script>    
}